### ISSUE TITLE
Where is the source?

### ISSUE THREAD

**Issue by buzztiaan** [Brandon506042/SonicRunnersReloaded#25]
I'd love to try porting it to linux

**Comment by rursache** [comment]
also porting to iOS

**Comment by Brandon506042** [comment]
There is no source code available, and I will not provide any.

**Comment by buzztiaan** [comment]
why not?

**Comment by buzztiaan** [comment]
ah, there is no sourcecode as its fully made in a freemium engine :D alright , guess i didnt google what 'click teamfusion' was

**Comment by buzztiaan** [comment]
but, for @rursache 's request, fusion 2.5 -does- have a iOS export

**Comment by rursache** [comment]
@buzztiaan indeed!
@Brandon506042 please export a iOS build and provide the IPA alongside the APK

**Comment by Brandon506042** [comment]
There will be no iOS version
